apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  labels:
    app: nginx-clusterip
    service: nginx-clusterip
spec:
  ports:
  - port: 9080
    name: http
    targetPort: 80
  selector:
    app: nginx
